"""
setup_databricks.py — Tạo bảng users & detections trên Databricks Unity Catalog.

Chạy script này MỘT LẦN trước khi khởi động Flask app.
Script sẽ:
  1. Drop & recreate tables (users, detections)
  2. Seed admin user (admin / admin123)
  3. Xóa user thừa (testuser, v.v.)
  4. Seed sample detections cho admin

Usage:
    python setup_databricks.py
"""

import os
import sys
from dotenv import load_dotenv
from databricks import sql as databricks_sql
from urllib.parse import urlparse, parse_qs

# Load .env
load_dotenv()

DATABASE_URL = os.environ.get('DATABASE_URL', '')
if not DATABASE_URL or 'databricks' not in DATABASE_URL:
    print("[ERROR] DATABASE_URL khong phai Databricks. Kiem tra file .env")
    sys.exit(1)

# Parse connection params
parsed = urlparse(DATABASE_URL)
host = parsed.hostname
token = parsed.password
params = parse_qs(parsed.query)
http_path = params.get('http_path', [''])[0]
catalog = params.get('catalog', ['hive_metastore'])[0]
schema = params.get('schema', ['default'])[0]

print(f"[INFO] Connecting to Databricks...")
print(f"  Host:     {host}")
print(f"  HTTP Path: {http_path}")
print(f"  Catalog:  {catalog}")
print(f"  Schema:   {schema}")

try:
    connection = databricks_sql.connect(
        server_hostname=host,
        http_path=http_path,
        access_token=token,
        catalog=catalog,
        schema=schema
    )
    cursor = connection.cursor()
    print("[OK] Connected to Databricks SQL Warehouse!\n")
except Exception as e:
    print(f"[ERROR] Cannot connect: {e}")
    sys.exit(1)


def run_sql(sql, description=""):
    try:
        cursor.execute(sql)
        print(f"  [OK] {description}")
        return True
    except Exception as e:
        err = str(e)
        if "ALREADY_EXISTS" in err.upper() or "already exists" in err.lower():
            print(f"  [SKIP] {description} (already exists)")
            return True
        else:
            print(f"  [ERROR] {description}: {e}")
            return False


# ============================================================
# STEP 1: Drop old tables
# ============================================================
print("[STEP 1] Dropping old tables (if exist)...")
run_sql(f"DROP TABLE IF EXISTS {catalog}.{schema}.detections", "Drop detections")
run_sql(f"DROP TABLE IF EXISTS {catalog}.{schema}.users", "Drop users")


# ============================================================
# STEP 2: Create tables (IDs generated by application)
# ============================================================
print("\n[STEP 2] Creating 'users' table...")
run_sql(f"""
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.users (
    id          BIGINT NOT NULL,
    email       STRING NOT NULL,
    username    STRING NOT NULL,
    password_hash STRING NOT NULL,
    role        STRING,
    is_active   BOOLEAN,
    created_at  TIMESTAMP,
    last_login  TIMESTAMP,
    birth_date  DATE,
    location    STRING
)
""", "Create users table")


print("\n[STEP 3] Creating 'detections' table...")
run_sql(f"""
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.detections (
    id               BIGINT NOT NULL,
    user_id          BIGINT NOT NULL,
    image_path       STRING NOT NULL,
    detection_type   STRING NOT NULL,
    objects_detected STRING NOT NULL,
    confidence_scores STRING,
    timestamp        TIMESTAMP,
    processing_time  DOUBLE
)
""", "Create detections table")


# ============================================================
# STEP 3: Seed admin user only
# ============================================================
print("\n[STEP 4] Seeding admin user...")

cursor.execute(f"SELECT COUNT(*) FROM {catalog}.{schema}.users WHERE username = 'admin'")
row = cursor.fetchone()
admin_exists = row[0] > 0 if row else False

if admin_exists:
    print("  [SKIP] Admin user already exists")
else:
    from werkzeug.security import generate_password_hash
    import time, random
    admin_hash = generate_password_hash('admin123')
    admin_hash_escaped = admin_hash.replace("'", "''")
    admin_id = int(time.time() * 1000) + random.randint(0, 999)

    cursor.execute(f"""
    INSERT INTO {catalog}.{schema}.users
        (id, email, username, password_hash, role, is_active, created_at, birth_date, location)
    VALUES
        ({admin_id}, 'admin@visionai.local', 'admin', '{admin_hash_escaped}', 'admin', TRUE, current_timestamp(), CAST('1995-06-15' AS DATE), 'TP. Ho Chi Minh')
    """)
    print(f"  [OK] Created admin user (admin / admin123) with id={admin_id}")


# ============================================================
# STEP 4: Delete non-admin users (testuser, etc.)
# ============================================================
print("\n[STEP 5] Deleting non-admin users...")
try:
    # First delete detections for non-admin users
    cursor.execute(f"""
    DELETE FROM {catalog}.{schema}.detections
    WHERE user_id IN (
        SELECT id FROM {catalog}.{schema}.users WHERE username != 'admin'
    )
    """)
    print("  [OK] Deleted detections for non-admin users")
except Exception as e:
    print(f"  [WARN] Could not delete non-admin detections: {e}")

try:
    cursor.execute(f"DELETE FROM {catalog}.{schema}.users WHERE username != 'admin'")
    print("  [OK] Deleted non-admin users")
except Exception as e:
    print(f"  [WARN] Could not delete non-admin users: {e}")


# ============================================================
# STEP 5: Seed sample detections for admin
# ============================================================
print("\n[STEP 6] Seeding sample detections for admin...")

cursor.execute(f"SELECT id FROM {catalog}.{schema}.users WHERE username = 'admin'")
admin_row = cursor.fetchone()
if admin_row:
    admin_id = admin_row[0]

    cursor.execute(f"SELECT COUNT(*) FROM {catalog}.{schema}.detections WHERE user_id = {admin_id}")
    det_count = cursor.fetchone()[0]

    if det_count > 0:
        print(f"  [SKIP] Admin already has {det_count} detections")
    else:
        import time, random

        # Detection 1: Object Upload
        det_id1 = int(time.time() * 1000) + random.randint(0, 999)
        cursor.execute(f"""
        INSERT INTO {catalog}.{schema}.detections (id, user_id, image_path, detection_type, objects_detected, confidence_scores, timestamp, processing_time)
        VALUES ({det_id1}, {admin_id}, 'seed_admin_object_01.jpg', 'upload',
            '[{{"name": {{"en": "person", "vi": "Người"}}, "confidence": 0.92, "class": "person"}}, {{"name": {{"en": "car", "vi": "Ô tô"}}, "confidence": 0.87, "class": "car"}}]',
            '[0.92, 0.87]', current_timestamp() - INTERVAL 28 DAYS, 0.145)
        """)
        print("  [OK] Detection 1: Object Upload (person + car)")

        # Detection 2: Camera
        det_id2 = int(time.time() * 1000) + random.randint(0, 999)
        cursor.execute(f"""
        INSERT INTO {catalog}.{schema}.detections (id, user_id, image_path, detection_type, objects_detected, confidence_scores, timestamp, processing_time)
        VALUES ({det_id2}, {admin_id}, 'seed_admin_camera_01.jpg', 'camera',
            '[{{"en": "laptop", "vi": "Máy tính xách tay"}}, {{"en": "cell phone", "vi": "Điện thoại"}}]',
            '[0.94, 0.88]', current_timestamp() - INTERVAL 25 DAYS, 0.098)
        """)
        print("  [OK] Detection 2: Camera (laptop + phone)")

        # Detection 3: Face Upload
        det_id3 = int(time.time() * 1000) + random.randint(0, 999)
        cursor.execute(f"""
        INSERT INTO {catalog}.{schema}.detections (id, user_id, image_path, detection_type, objects_detected, confidence_scores, timestamp, processing_time)
        VALUES ({det_id3}, {admin_id}, 'seed_admin_face_01.jpg', 'face_upload',
            '[{{"box": [150, 80, 200, 220], "confidence": 0.95, "name": "Admin"}}]',
            '[0.95]', current_timestamp() - INTERVAL 22 DAYS, 0.067)
        """)
        print("  [OK] Detection 3: Face Upload")

        # Detection 4: Color Detection
        det_id4 = int(time.time() * 1000) + random.randint(0, 999)
        cursor.execute(f"""
        INSERT INTO {catalog}.{schema}.detections (id, user_id, image_path, detection_type, objects_detected, confidence_scores, timestamp, processing_time)
        VALUES ({det_id4}, {admin_id}, 'seed_admin_color_01.jpg', 'color',
            '[{{"rgb": [41, 128, 185], "hex": "#2980b9", "name": "Blue", "percentage": 35.42}}, {{"rgb": [236, 240, 241], "hex": "#ecf0f1", "name": "White", "percentage": 28.15}}]',
            '[35.42, 28.15]', current_timestamp() - INTERVAL 18 DAYS, 0.034)
        """)
        print("  [OK] Detection 4: Color Detection")

        # Detection 5: Classification
        det_id5 = int(time.time() * 1000) + random.randint(0, 999)
        cursor.execute(f"""
        INSERT INTO {catalog}.{schema}.detections (id, user_id, image_path, detection_type, objects_detected, confidence_scores, timestamp, processing_time)
        VALUES ({det_id5}, {admin_id}, 'seed_admin_class_01.jpg', 'classification',
            '[{{"name": "dog", "confidence": 0.91, "box": [50, 100, 400, 350]}}, {{"name": "person", "confidence": 0.82, "box": [420, 60, 600, 440]}}]',
            '[0.91, 0.82]', current_timestamp() - INTERVAL 12 DAYS, 0.078)
        """)
        print("  [OK] Detection 5: Classification (dog + person)")

else:
    print("  [ERROR] Admin user not found, cannot seed detections")


# ============================================================
# STEP 6: Verify
# ============================================================
print("\n[STEP 7] Verifying tables...")

cursor.execute(f"SELECT COUNT(*) FROM {catalog}.{schema}.users")
user_count = cursor.fetchone()[0]
print(f"  Users table: {user_count} rows")

cursor.execute(f"SELECT COUNT(*) FROM {catalog}.{schema}.detections")
det_count = cursor.fetchone()[0]
print(f"  Detections table: {det_count} rows")

cursor.execute(f"SELECT id, username, email, role FROM {catalog}.{schema}.users")
rows = cursor.fetchall()
for r in rows:
    print(f"    -> id={r[0]}, username={r[1]}, email={r[2]}, role={r[3]}")

cursor.close()
connection.close()

print("\n" + "=" * 50)
print("[OK] Setup complete! Tables ready on Databricks.")
print(f"   Catalog: {catalog}")
print(f"   Schema:  {schema}")
print(f"   Tables:  users ({user_count}), detections ({det_count})")
print("=" * 50)
print("\nChay 'python run.py' de khoi dong Flask app.")
