-- data/08_databricks_seed_sql_serverless.sql
-- Kịch bản khởi tạo dữ liệu cho Databricks SQL Serverless (Phiên bản chỉ dùng SQL, không cần Cluster PySpark)

-- 1. CHUẨN BỊ MÔI TRƯỜNG (Unity Catalog)
-- Lưu ý: Nếu tài khoản Free edition của bạn không hỗ trợ tạo Catalog, hãy bỏ qua dòng CREATE CATALOG
-- và đổi lệnh USE CATALOG mang cụm từ mặc định như 'hive_metastore'
CREATE CATALOG IF NOT EXISTS vision_ai_catalog;
USE CATALOG vision_ai_catalog;

CREATE SCHEMA IF NOT EXISTS default_db;
USE SCHEMA default_db;

-- ========================================================
-- 2. TẠO BẢNG USERS (Người Tương Tác) BẰNG DELTA LAKE
-- ========================================================
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  email STRING NOT NULL,
  username STRING NOT NULL,
  password_hash STRING NOT NULL,
  role STRING DEFAULT 'user',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP,
  last_login TIMESTAMP,
  birth_date DATE,
  location STRING
) USING DELTA
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');

-- (Optional) Xóa dữ liệu cũ nếu muốn chạy lại script nhiều lần
TRUNCATE TABLE users;

-- Chèn Dữ liệu Người Dùng
INSERT INTO users (email, username, password_hash, role, is_active, created_at, birth_date, location) VALUES
(
  'admin@visionai.com', 
  'admin', 
  concat('pbkdf2:sha256:600000', chr(36), 'I9aPwiHzacjm5I14', chr(36), '1e42df90c142e944c7da7c98891c3d2755ace99423404e91fffce8a749f20ef9'), 
  'admin', 
  true, 
  current_timestamp() - INTERVAL 30 DAYS, 
  cast('1995-06-15' as date), 
  'TP. Hồ Chí Minh'
),
(
  'analyst@visionai.com', 
  'analyst', 
  concat('pbkdf2:sha256:600000', chr(36), 'riAn0PKGLhnzretH', chr(36), '83f67b971063b2ee3d84a44336868115e8c0a5a031a2a2e9de82520f5597ed4e'), 
  'user', 
  true, 
  current_timestamp() - INTERVAL 20 DAYS, 
  cast('1998-03-22' as date), 
  'Hà Nội'
);

-- ========================================================
-- 3. TẠO BẢNG DETECTIONS (Lịch Sử Nhận Diện) BẰNG DELTA LAKE
-- ========================================================
CREATE TABLE IF NOT EXISTS detections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  user_id INT NOT NULL,
  image_path STRING NOT NULL,
  detection_type STRING NOT NULL,
  objects_detected STRING NOT NULL,
  confidence_scores STRING,
  timestamp TIMESTAMP,
  processing_time FLOAT
) USING DELTA;

TRUNCATE TABLE detections;

-- Chèn dữ liệu Lịch sử Nhận diện bằng cách Query lấy ID từ bảng users
-- (Để đảm bảo khóa ngoại chính xác nếu ID sinh tự động)
INSERT INTO detections (user_id, image_path, detection_type, objects_detected, confidence_scores, timestamp, processing_time)
SELECT 
  id as user_id, 
  'seed_admin_object_01.jpg', 
  'upload', 
  '[{"name": {"en": "person", "vi": "Người"}, "confidence": 0.92, "class": "person"}, {"name": {"en": "car", "vi": "Ô tô"}, "confidence": 0.87, "class": "car"}]', 
  '[0.92, 0.87]', 
  current_timestamp() - INTERVAL 28 DAYS, 
  CAST(0.145 AS FLOAT)
FROM users WHERE username = 'admin';

INSERT INTO detections (user_id, image_path, detection_type, objects_detected, confidence_scores, timestamp, processing_time)
SELECT 
  id as user_id, 
  'seed_admin_face_01.jpg', 
  'face_upload', 
  '[{"box": [150, 80, 200, 220], "confidence": 0.95, "name": "Admin"}]', 
  '[0.95]', 
  current_timestamp() - INTERVAL 25 DAYS, 
  CAST(0.067 AS FLOAT)
FROM users WHERE username = 'admin';

INSERT INTO detections (user_id, image_path, detection_type, objects_detected, confidence_scores, timestamp, processing_time)
SELECT 
  id as user_id, 
  'seed_analyst_object_01.jpg', 
  'upload', 
  '[{"name": {"en": "motorcycle", "vi": "Xe máy"}, "confidence": 0.93, "class": "motorcycle"}]', 
  '[0.93]', 
  current_timestamp() - INTERVAL 18 DAYS, 
  CAST(0.167 AS FLOAT)
FROM users WHERE username = 'analyst';

-- ========================================================
-- 4. KIỂM TRA LẠI DỮ LIỆU
-- ========================================================
SELECT 
  u.username,
  d.detection_type,
  d.objects_detected,
  d.timestamp
FROM users u
LEFT JOIN detections d ON u.id = d.user_id
ORDER BY d.timestamp DESC;
